title: CSS advanced Final
email: Iskren.1990@abv.bg
description: CSS advanced sample site

baseurl: "CSS-Variables-and-Font-Icons-Lab/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
destination: docs
twitter_username: Iskren
github_username:  Iskren Stanchev

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
